version: '3.1'

services:
  aqua-matrix-bot:
    #restart: always
    #image: avi0n/aqua-matrix-bot
    build: .
    container_name: aqua-matrix-bot
    volumes:
      - ./bot/data:/opt/aqua/data/
      # Change the location of the SQLite database files 
      # by replacing "./bot/db" with your custom path
      - ./bot/db:/opt/aqua/db

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
